---
version: 2
models:
- name: "model_L2_clinical_trial_gap_analysis_total_cost_by_diagnosis"
  tags:
  - "prophecy_temp"
- name: "model_L2_clinical_trial_gap_analysis_total_cost_by_diagnosis"
  tags:
  - "prophecy_temp"
- name: "model_L2_clinical_trial_gap_analysis_cleanse_diagnosis_data"
  tags:
  - "prophecy_temp"
- name: "model_L2_clinical_trial_gap_analysis_diagnosis_cost_summary_sorted"
  tags:
  - "prophecy_temp"
- name: "model_L2_clinical_trial_gap_analysis_empty_nctids_summary"
  tags:
  - "prophecy_temp"
- name: "model_L2_clinical_trial_gap_analysis_total_cost_desc"
  tags:
  - "prophecy_temp"
- name: "model_L2_clinical_trial_gap_analysis_diagnosis_cost_summary"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_L2_clinical_trial_gap_analysis_source"
  database: "prophecy_sql_workshop_clone"
  schema: "healthcare_sample"
  tags:
  - "prophecy_temp"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_L2_clinical_trial_gap_analysis_post_diagnosis_cost_summary_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_L2_clinical_trial_gap_analysis_post_diagnosis_cost_summary_sorted_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_L2_clinical_trial_gap_analysis_post_total_cost_by_diagnosis_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_L2_clinical_trial_gap_analysis_post_total_cost_desc_0"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_L2_clinical_trial_gap_analysis_pre_diagnosis_clinical_study_join_0"
    tags:
    - "prophecy_temp"
